package hotreload

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// ConfigFile is the conventional Air configuration filename.
const ConfigFile = ".air.toml"

const airConfig = `# .air.toml - generated by fw
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd"
  entrypoint = ["./tmp/main"]
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  include_ext = ["env", "go", "json", "toml", "yaml", "yml"]
  kill_delay = "1s"
  send_interrupt = true
  stop_on_error = true

[build.windows]
  cmd = "go build -o ./tmp/main.exe ./cmd"
  entrypoint = ["tmp\\main.exe"]

[log]
  time = false

[misc]
  clean_on_exit = true
`

// EnsureConfig creates an Air configuration in dir without replacing an
// existing project configuration. It reports whether a file was created.
func EnsureConfig(dir string) (bool, error) {
	path := filepath.Join(dir, ConfigFile)
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if errors.Is(err, os.ErrExist) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("create Air configuration: %w", err)
	}

	written, writeErr := file.WriteString(airConfig)
	if writeErr == nil && written != len(airConfig) {
		writeErr = io.ErrShortWrite
	}
	closeErr := file.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		removeErr := os.Remove(path)
		if errors.Is(removeErr, os.ErrNotExist) {
			removeErr = nil
		}
		return false, errors.Join(fmt.Errorf("write Air configuration: %w", err), removeErr)
	}
	return true, nil
}
