package hotreload

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// ConfigFile is the conventional Air configuration filename.
const ConfigFile = ".air.toml"

const airConfig = `# .air.toml - generated by fw
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd"
  entrypoint = ["./tmp/main"]
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  include_ext = ["env", "go", "json", "toml", "yaml", "yml"]
  kill_delay = "1s"
  send_interrupt = true
  stop_on_error = true

[build.windows]
  cmd = "go build -o ./tmp/main.exe ./cmd"
  entrypoint = ["tmp\\main.exe"]

[log]
  time = false

[misc]
  clean_on_exit = true
`

// EnsureConfig creates an Air configuration in dir without replacing an
// existing project configuration. It reports whether a file was created.
func EnsureConfig(dir string) (bool, error) {
	path := filepath.Join(dir, ConfigFile)
	if _, err := os.Stat(path); err == nil {
		return false, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("inspect Air configuration: %w", err)
	}

	if err := os.WriteFile(path, []byte(airConfig), 0o644); err != nil {
		return false, fmt.Errorf("write Air configuration: %w", err)
	}

	return true, nil
}
