package cli

import (
	"fmt"
	"os"
	"os/exec"
	"syscall"

	"github.com/spf13/cobra"
)

var airToml = `# .air.toml — generated by fw dev
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  include_ext = ["go", "yaml", "yml"]
  kill_delay = "0s"
  send_interrupt = true

[log]
  time = false

[misc]
  clean_on_exit = true
`

var devCmd = &cobra.Command{
	Use:   "dev",
	Short: "Run the app with hot reload (requires air)",
	RunE: func(cmd *cobra.Command, args []string) error {
		airPath, err := exec.LookPath("air")
		if err != nil {
			fmt.Println("air is not installed. Install it with:")
			fmt.Println()
			fmt.Println("  go install github.com/air-verse/air@latest")
			fmt.Println()
			return fmt.Errorf("air not found in PATH")
		}

		if _, err := os.Stat(".air.toml"); os.IsNotExist(err) {
			fmt.Println("  create .air.toml")
			if err := os.WriteFile(".air.toml", []byte(airToml), 0644); err != nil {
				return fmt.Errorf("failed to write .air.toml: %w", err)
			}
		}

		return syscall.Exec(airPath, []string{"air"}, os.Environ())
	},
}

func init() {
	rootCmd.AddCommand(devCmd)
}
